/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arrays.h"

respuesta_notas *obtener_notas_1_svc(indices_notas *argp, struct svc_req *rqstp)
{
	static respuesta_notas  result;
	int i;

	/*
	 * insert server code here
	 */
	fprintf(stderr, "------ Desde el Servidor -------\n");

	for(i=0;i<MAXIMO;i++) {
		fprintf(stderr, "indices[%d]=%d\n", i,argp->indices.indices_val[i]);
	}

	// Hay que dar memoria y rellenar la longitud del array, las 2 cosas
	result.notas.notas_val = malloc(sizeof(float)*MAXIMO);
	result.notas.notas_len = MAXIMO;
	
	for(i=0;i<MAXIMO;i++) {
		result.notas.notas_val[i] = argp->indices.indices_val[i]*10.0;
		fprintf(stderr, "v[%d]=%f\n", i,result.notas.notas_val[i]);
	}
	

	return &result;
}
