/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

int *sumar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 + argp->arg2;

	return &result;
}

int *restar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 - argp->arg2;

	return &result;
}

int *multiplicar_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	result = argp->arg1 * argp->arg2;

	return &result;
}

int *dividir_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;

	if(argp->arg2!=0) {
		result = argp->arg1/argp->arg2;
	}
	else return((int *)NULL);

	return &result;
}
