/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void calculadora_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	entrada  sumar_1_arg;
	int  *result_2;
	entrada  restar_1_arg;
	int  *result_3;
	entrada  multiplicar_1_arg;
	int  *result_4;
	entrada  dividir_1_arg;

	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}


	sumar_1_arg.arg1 = 5;
	sumar_1_arg.arg2 = 8;
	result_1 = sumar_1(&sumar_1_arg, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	} else printf("Suma=%d\n", *result_1);

	restar_1_arg.arg1 = 11;
	restar_1_arg.arg2 = 7;
	result_2 = restar_1(&restar_1_arg, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
	} else printf("Resta=%d\n", *result_2);

	multiplicar_1_arg.arg1 = 4;
	multiplicar_1_arg.arg2 = 5;
	result_3 = multiplicar_1(&multiplicar_1_arg, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
	} else printf("Multiplicacion=%d\n", *result_3);

	dividir_1_arg.arg1 = 16;
	dividir_1_arg.arg2 = 2;
	result_4 = dividir_1(&dividir_1_arg, clnt);
	if (result_4 == NULL) {
		clnt_perror(clnt, "call failed:");
	} else printf("Division=%d\n", *result_4);

	clnt_destroy (clnt);

}


int main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calculadora_1 (host);
exit (0);
}
