/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "holamundo.h"
#include <string.h>

char nombre[20];

char **hola_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result;	

	/*
	 * insert server code here
	 */
	fprintf(stderr,"Recibido en el servidor: %s\n", *argp);	
	strcpy(nombre, "Hola ");	
	strcat(nombre, *argp);
	result = nombre;

	return &result;
}
