/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"

bool_t
xdr_entrada (XDR *xdrs, entrada *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->vector.vector_val, (u_int *) &objp->vector.vector_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
