/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calculadora_1(char *host,int *vector,int tam)
{
	CLIENT *clnt;
	float  *result_1;
	entrada  arg;
	int  *result_2;
	int  *result_3;
	
	int factorial_1_arg= vector[0];
	int i;
	
	arg.vector.vector_val=malloc(sizeof(int)*tam);
	arg.vector.vector_len= tam;
	for(i=0;i<tam;i++)
		arg.vector.vector_val[i] = vector[i];
#ifndef	DEBUG
//aqui se crea la conexion con el servidor
	clnt = clnt_create (host, CALCULADORA, CALCULADORA_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = media_1(&arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = maximo_1(&arg, clnt);
	if (result_2 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = factorial_1(&factorial_1_arg, clnt);
	if (result_3 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	printf("Media: %f \nMaximo: %d\nFactorial: %d\n",*result_1,*result_2,*result_3);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int i;
	int *vector;
	vector = (int *) malloc ((argc-2)*sizeof(int));
	
	if (argc < 3) {
		printf ("usage: %s server_host [lista_numeros]\n", argv[0]);
		exit (1);
	}
	
	for(i=0;i<argc-2;i++)
		vector[i] = atoi(argv[i+2]);
		
	host = argv[1];
	calculadora_1 (host,vector,argc-2);
exit (0);
}
