/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
media_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static float  result;

	float sumatorio = 0.0;
	int i;
	for(i=0;i<argp->vector.vector_len;i++)
		sumatorio+=argp->vector.vector_val[i];
		
	result=sumatorio/argp->vector.vector_len;

	return &result;
}

int *
maximo_1_svc(entrada *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;
	result=argp->vector.vector_val[0];
	for(i=0;i<argp->vector.vector_len;i++){	
		if(result<argp->vector.vector_val[i])
			result=argp->vector.vector_val[i];
	}
	
	return &result;
}

int *
factorial_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result=1;

	int i;
	
	for(i=*argp;i>1;i--)	
		result*=i;

	return &result;
}
